#!/bin/bash

# script specific functions
# make use of script defined globals

Noforce_Alert ()
{
    Is_True ${FORCE} || UI_Passive_Alert "${*}"
}

UI_Backup_Alert ()
{
    Is_True ${FORCE} && return 0
    if [[ "${BACKUP_MODE}" == "${DEFAULT_BACKUP_MODE}" ]]
    then
        UI_Passive_Alert "$(echo ${*} "(backups will be made):")"
    else
        UI_Passive_Alert "$(echo ${*}):"
    fi
}

Install_Package_From_AUR_Helper () { sudo ${AUR_HELPER} -Sq --noconfirm "${1}"; }

Remove_Item_From_File ()
{
    local _item_name="${1}"
    local _filepath="${2}"
    # yes, twice. there's probably a better sed pattern to deal with all cases
    sed -i "/^[[:space:]]*#/!s/\<${_item_name}\>[^[:punct:]]//" "${_filepath}"
    sed -i "/^[[:space:]]*#/!s/\<${_item_name}\>$//" "${_filepath}"
}

Files_Differ ()
{
    local _filepath_1="${1}"
    local _filepath_2="${2}"
    $(diff -q "${_filepath_1}" "${_filepath_2}" &>/dev/null) && return 1 || return 0
}
